# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsyX93dzRyGVXD9Oxhmb07K60CwWFJQ0
"""

# HOUSE PREDICTION (PROJECT)
#NAME : Dhakshinamurthy

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 1. Load the dataset
# Ensure 'housing.csv' is in your working directory
df = pd.read_csv("/content/housing.csv.zip")

# 2. Data Cleaning: Handle missing values
# The 'total_bedrooms' column has some missing entries; we fill them with the median.
df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].median())

# 3. Feature Engineering: Convert categorical data to numerical
# The 'ocean_proximity' column is text; we use One-Hot Encoding to make it numeric.
df_encoded = pd.get_dummies(df, columns=['ocean_proximity'])

# 4. Split Data into Features (X) and Target (y)
X = df_encoded.drop('median_house_value', axis=1)
y = df_encoded['median_house_value']

# 5. Split into Training and Testing sets (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6. Initialize and Train the Model (Changed to RandomForestRegressor for feature importance)
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


# 7. Make Predictions on the Test Set
y_pred = model.predict(X_test)

# 8. Evaluate Model Performance
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Model Performance:")
print(f"------------------")
print(f"Root Mean Squared Error (RMSE): ${rmse:,.2f}")
print(f"R-squared Score: {r2:.4f}")

# 9. (Optional) View Feature Importance
importances = pd.DataFrame({'Feature': X.columns, 'Importance': model.feature_importances_})
print("\nTop Features Contributing to Price:")
print(importances.sort_values(by='Importance', ascending=False).head(5))